- trajopt/include/trajopt/kinematic_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
I ran into this issue on 32 bit machines but did think it was an issue on 64 bit machines for some reason. I thing I have all of the struct/classes that have fixed size eigen member variables.
@mpowelson You may give the package a once over along with tesseract looking for classes/structs that have fixed size eigen member types.
> Add EIGEN_MAKE_ALIGNED_OPERATOR_NEW macro

- trajopt/CMakeLists.txt
- trajopt/include/trajopt/problem_description.hpp
- trajopt/include/trajopt/trajectory_costs.hpp
- trajopt/src/problem_description.cpp
- trajopt/src/trajectory_costs.cpp
- trajopt/test/costs_unit.cpp
- trajopt/test/costs_unit.launch
- trajopt_sco/include/trajopt_sco/modeling.hpp
- trajopt_sco/include/trajopt_sco/modeling_utils.hpp
- trajopt_sco/src/modeling.cpp
- trajopt_sco/src/modeling_utils.cpp
- trajopt_utils/include/trajopt_utils/eigen_conversions.hpp
- trajopt_utils/include/trajopt_utils/vector_ops.hpp
@Levi-Armstrong I wanted to get your thoughts on this. Currently only joint velocity eq/ineq cost/cnt are implemented. Once we get that the way we like, I figured it will be easy to copy for the others.
The term is centered about targs. If no limits are given, it is an equality term. If limits are given, then it is an iequality term with the hinges at targ+upper_lim and targ+lower_lim (lower_lim should be negative). It seems to pass all of the current tests, but I don't think the inequality is really being tested anywhere.
Still TODO:
- first_step/last_step is unimplemented
- Probably need some checks to make sure limits are correct sign
- Expand to the rest of the terms
> Joint cost updates

- trajopt/src/problem_description.cpp
- trajopt_examples/config/basic_cartesian_plan.json
- trajopt_examples/config/glass_up_right_plan.json
- trajopt_test_support/config/arm_around_table.json
- trajopt_test_support/config/arm_around_table_continuous.json
- trajopt_test_support/config/box_cast_test.json
The idea is that we want at least one parameter that must be set for each cost/cnt. It didn't seem to make much sense that coeff was that value. Explicitly setting the target and letting coeff default to 1 seemed like a better idea.
> Remove the default target = 0 from joint cost/constraints and add default coeff = 1

- trajopt/CMakeLists.txt
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
- trajopt/test/costs_unit.cpp
- trajopt/test/interface_unit.cpp
- trajopt/test/interface_unit.launch
- trajopt_examples/config/glass_up_right_plan.json
- trajopt_examples/src/basic_cartesian_plan.cpp
- trajopt_examples/src/car_seat_demo.cpp
- trajopt_examples/src/glass_up_right_plan.cpp
- trajopt_examples/src/puzzle_piece_auxillary_axes_plan.cpp
- trajopt_examples/src/puzzle_piece_plan.cpp
- trajopt_test_support/config/arm_around_table_time.json
Time param sections are still skeletons. But it doesn't appear to have broken anything without time.
> Integrate time param - term type switch

- trajopt_sco/src/osqp_interface.cpp
This keeps it from spamming the terminal when running TrajOpt many times in a row.
> Set OSQP verbosity to false

- trajopt_sco/src/gurobi_interface.cpp
Change string to std::string and some minor clang fixes. There are still more clang warnings that need to be addressed.
> Fixes in gurobi interface

- trajopt/src/problem_description.cpp
Otherwise one gets
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::bad_format_string> >'
what():  boost::bad_format_string: format-string is ill-formed
```
> Fix format string

- trajopt/include/trajopt/utils.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt_sco/include/trajopt_sco/bpmpd_io.hpp
This was an oversight on my part when I added the ability to add link specific distance threshold. The filtering was occurring in convex and value function but not in the calcCollision so cost function were being added for pairs that were outside the threshold. This was causing issues because cost returned from the value function and the sum of the constants from the cost function were not even close as a result. This was causing issues with the optimizer as you would expect.
Also this fixes an issues I ran into with a return type.
> Fix calcCollision to filter link specific distance threshold

- trajopt/include/trajopt/plot_callback.hpp
- trajopt/src/plot_callback.cpp
This is important when using Tesseract Planner, and you do not have access to the problem at creation time.
> Add Plot Callback that doesn't require the problem

- trajopt/src/problem_description.cpp
The `DynamicCartPoseErrCalculator` class was previously not being constructed with the target TCP transform, thus all target points sat at the origin of the frame they were associated with
> Dynamic Cartesian Pose Error Calculator Update

- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
I would like to propose the following change: add the `OptStatus` field to `TrajOptResult`. Right now, using `OptimizeProblem` is a useful convenience function that sets quite a few defaults automatically, but the result struct it returns is incomplete. Indeed, it's pretty much impossible to understand if the optimization succeeded or not based on only the trajectory, costs and constraints values.
Let me know what you think!
> Add OptStatus to TrajOptResult

- .travis.yml
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
- trajopt/test/data/config/numerical_ik1.json
This PR updates the Cartesian pose term info to be constructed from a transformation that is relative to an arbitrary frame that exists in the environment (rather than a transformation relative to the base frame of the kinematic chain)
> Cartesian Pose Term Info from frame relative transform

- trajopt/src/problem_description.cpp
If target is empty string it is assumed to be in world coordinates and should not try and loop up the link. This was missed in PR #130.
> Fix CartPoseTermInfo empty target

- trajopt/include/trajopt/utils.hpp
It seems that for the version of Eigen installed with ROS Kinetic (at least on my machine), converting a rotation matrix to angle-axis representation does not return an angle guaranteed to be on [-pi, pi]. This PR adds the necessary checks/operations for ensuring that the rotation angle lies within [-pi, to pi]
> Orientation error calculation fix

- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/interface_unit.cpp
- trajopt/test/joint_costs_unit.cpp
- trajopt/test/kinematic_costs_unit.cpp
- trajopt/test/planning_unit.cpp
This pull request updates `trajopt_ros` to work with https://github.com/ros-industrial-consortium/tesseract/pull/172.
> Use ResourceLocator instead of ResourceLocaterFn in tesseract unit tests

- trajopt/src/problem_description.cpp
- trajopt_sco/include/trajopt_sco/optimizers.hpp
- trajopt_sco/src/optimizers.cpp
- trajopt_sco/test/small-problems-unit.cpp
This pull request changes the way that constraints are inflated. Rather than inflating constraints uniformly if they are not satisfied when the optimization converges, this inflates only the constraints that failed. This could allow the optimization to get out of local minima more easily. Currently, local minima that are caused by competing constraints are still local minima after they are uniformly scaled. 
This is WIP because it depends on the clang-tidy pull request. It should also probably be tested again before merging as it has not been tested since being rebased.
> WIP: Inflate only the constraints that failed

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
This enables avoiding moving objects to moving objects when continuous collision checking is enabled.
> Enable continuous collision checking for moving to moving objects

- trajopt_sco/src/osqp_interface.cpp
Since [version 0.6.0](https://github.com/oxfordcontrol/osqp/releases/tag/v0.6.0) OSQP's interface has changed. `osqp_setup` now returns an error code and fills in the workspace (which is now a pointer to pointer). This is the minimum change required to make this work, but I guess this PR is more a discussion:
- How should the deprecation / version change be handled?
- Properly taking into account the return code requires a number of tweaks to the interface, I'm not sure I understand the ramifications so I'd like some guidance.
> Update interface to OSQP 0.6.0

- trajopt/src/collision_terms.cpp
Reading through the old repository this was carried over because Bullet added this margin to the contact shapes. This makes since in the case of solving for the exact point of contact but is not required just for contact checking so removing. This should speed up the optimization for chases where you are always in close proximity.
> Remove the additional 0.04 added to contact distance threshold

- trajopt_ext/osqp/CMakeLists.txt
- trajopt_ext/osqp/package.xml
- trajopt_sco/src/solver_interface.cpp
Gurobi is still the preferred solver, but the default solver assuming no other setup has been done on the computer will now be OSQP. This has been added to Trajopt_ext. If OSQP is not found at compile time, it will clone it into the build directory and compile it. 
The motivation behind this is that BPMPD has a noncommercial license. By changing the default solver to OSQP we limit the chance that someone uses BPMPD in a commercial application inadvertently. It will now require an intentional change.
The new order for AUTO_SOLVER is 
* Gurobi
* OSQP
* BPMPD
* qpOASES
> Change Default Solver

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/include/trajopt/trajectory_costs.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt/src/trajectory_costs.cpp
- trajopt/test/data/config/arm_around_table.json
- trajopt/test/data/config/arm_around_table_continuous.json
- trajopt/test/data/config/arm_around_table_time.json
- trajopt/test/data/config/box_cast_test.json
This updates casted collision evaluator to handle fixed start or end states. Before we just would exclude but that is not ideal because you would periodically get post check failures  between the start and first waypoint and next to last waypoint and the end waypoint. 
Also this PR includes updating the constructors to pass eigen types by reference. The documentation states not to pass eigen types by value and I know in the past we have had eigen issues.
> Update casted collision evaluator to handle fixed start and end states

- trajopt_sco/include/trajopt_sco/osqp_interface.hpp
- trajopt_sco/src/osqp_interface.cpp
Apparently OSQP allocates A and P leaving us to deallocated them. This PR adds 2 unique_ptrs to replace take ownership of them rather than leaving them as raw ptrs.
> Add unique_ptrs A and P to osqp interface

- trajopt_sco/src/solver_utils.cpp
Problem setup takes a very long time when the number of affine expressions is very large, for example if there are many link pairs that could be in collision and multiple costs or constraints are assigned per pair. I'd like to benchmark this more thoroughly, but as an example a problem with about 5000 variables and 10000 constraints took about 60s to set up and then about 1 second to solve.
The reason for this is that the function for composing Eigen sparse matrices from affine expression vectors uses a very inefficient method for inserting new elements. [According to the Eigen documentation](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html), the `coeffRef` function performs a binary search on the matrix when inserting each new element to make sure that there is not already an …
> Improve efficiency of sparse matrix initialization

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt_sco/package.xml
- trajopt_sco/src/optimizers.cpp
Adds a `safety_margin_buffer` parameter to the Trajopt collision evaluators. This is an additional buffer that is added to the safety margin when checking if contacts should be evaluated as collisions. Contact distances within `safety_margin + safety_margin_buffer` will be evaluated by the optimization but will not contribute a cost. The purpose of this change is to help the optimization stay out of collision when the safety margin distance is very small. The default value is set to 0.05m.
Other changes:
- Fix a missing OSQP dependency in `trajopt_sco`
- Fix a bug where the optimization would fail in cases when it actually converged with all constraints satisfied.
> Add a safety margin buffer to collision evaluators

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/include/trajopt/typedefs.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
The current implementation for the collision term added an equation for each contact results. This means for a given link pair it could have multiple contacts if the links contain multiple collision objections. This results in a large number of equation to solve for some environments. This enables the ability to use the weighted sum for a given link pair so you only end up with one equation per link pair significantly reducing the number of equations to solve.
> Add ability to use weighted sum jacobian calculation for contact link pairs

- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
The unit tests were broken in a recent Tesseract PR.
> Use std::move when calling addLink

- trajopt/src/problem_description.cpp
Allow either 1 x DOF or DOF x 1. Previously it would segfault if you gave it a TrajArray corresponding to one joint position (a single row).
> Check init_info.data.size() when using JOINT_INTERPOLATED

- trajopt/src/collision_terms.cpp
- trajopt/test/planning_unit.cpp
- trajopt_sco/src/osqp_interface.cpp
This PR fixes a bug where the `cc_time` of the second link in a collision pair was being indexed incorrectly. It also replaces code with for loop since the same operations are applied to both collision links
> Collision Interpolation Bug Fix

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/kinematic_terms.cpp
This exposed the ability to get the gradient from the collision evaluator to support alternative use cases. It reduce code duplication within the evaluator.
> Add GetGradient function to CollisionEvaluator

- trajopt_sco/CMakeLists.txt
- trajopt_sco/cmake/FindGUROBI.cmake
- trajopt_sco/include/trajopt_sco/solver_interface.hpp
- trajopt_sco/src/bpmpd_interface.cpp
- trajopt_sco/src/gurobi_interface.cpp
- trajopt_sco/src/osqp_interface.cpp
- trajopt_sco/src/qpoases_interface.cpp
- trajopt_sco/src/solver_interface.cpp
- trajopt_sco/src/solver_utils.cpp
- Update `FindGUROBI.cmake` to find Gurobi 9.0 and to more generally match the example Gurobi provides [here](https://support.gurobi.com/hc/en-us/articles/360039499751-CMake-C-C-compilation-of-Gurobi-projects).
- Change the `vars2inds` and `cnts2inds` functions so they returns void and writes the output vector of indices to a parameter. Added new versions of these function that output a `SizeTVec`, which complements the existing functions that outputs a `IntVec`. This is a solution to the return type issue described in #168.
- Modify usages of these functions to reflect new return type and parameters.
- Add `static_cast`s where warnings were complaining about implicit conversions between types changing values.
> Fixes for Gurobi 9.0.1

- README.md
- trajopt/include/trajopt/collision_terms.hpp
- trajopt/src/collision_terms.cpp
- trajopt_utils/cmake/trajopt_macros.cmake
This adds CalcCollision functions to the TrajOpt collision evaluators that take only Eigen types. This allows them to be used outside of the current Trajopt setup (and independently of Vars). Note that the constructor still requires that a VarVector be passed in (it can be empty if using the evaluator this way). We may want to revisit this with a more comprehensive refactor if we ever pursue something like IFOPT to break the dependency on sco.
> Add CalcCollisions that takes only joint values instead of Vars

- .travis.yml
- README.md
- trajopt/CMakeLists.txt
- trajopt/package.xml
- trajopt/test/benchmarks/CMakeLists.txt
- trajopt/test/benchmarks/joint_term_benchmarks.cpp
- trajopt_utils/cmake/trajopt_macros.cmake
Adds a Google benchmark for the Joint Terms. 
To output to CSV
```
./trajopt_joint_term_benchmark --benchmark_format=csv > trajopt_joint_term_benchmark.csv
```
An example terminal output looks like below. 
```
You can set logging level with TRAJOPT_LOG_THRESH. Valid values: FATAL ERROR WARN INFO DEBUG TRACE. Defaulting to ERROR
Run on (20 X 4100 MHz CPU s)
2020-04-02 11:53:14
***WARNING*** Library was built as DEBUG. Timings may be affected.
---------------------------------------------------------------------------------------------------
Benchmark                                                            Time           CPU Iterations
---------------------------------------------------------------------------------------------------
BM_EQ_TERM_CONSTRUCTION<trajopt::JointPosEqCost> …
```
> Add Joint Term Benchmarks

- trajopt/include/trajopt/collision_terms.hpp
Otherwise it calls the base class which can lead to perplexing errors when using methods not in the base class.
> Add Ptr and ConstPtr to collision evaluator implementations

- trajopt/test/kinematic_costs_unit.cpp
This function is not being used because it was not working correctly. Now it is segfaulting in the unit test. Disabling the test until we get it figured out.
> Disable DynamicCartPoseJacCalculator test

- .travis.yml
- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/trust_region_sqp_solver.h
- trajopt_optimizers/trajopt_sqp/src/trust_region_sqp_solver.cpp
We needed some way of initializing when not using the Solve method now that results_ is private.
> Add init method to trust region sqp solver

- trajopt/colcon.pkg
- trajopt_ext/osqp/colcon.pkg
- trajopt_ext/osqp_eigen/colcon.pkg
- trajopt_ext/vhacd/colcon.pkg
- trajopt_ifopt/colcon.pkg
- trajopt_optimizers/trajopt_sqp/colcon.pkg
- trajopt_sco/colcon.pkg
- trajopt_tools/colcon.pkg
- trajopt_utils/cmake/trajopt_macros.cmake
- trajopt_utils/colcon.pkg
Fixes rosdep issues when building trajopt in an extended workspace.
> Add Colcon environment hooks

- README.md
As per subject.
Took me some time to find it again, and the readme here seemed to be pointing me to the training exercises.
> readme: link to where we keep trajopt_examples (since #108)

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/src/collision_terms.cpp
- trajopt_ifopt/include/trajopt_ifopt/constraints/cartesian_position_constraint.h
- trajopt_ifopt/include/trajopt_ifopt/constraints/collision_constraint.h
- trajopt_ifopt/include/trajopt_ifopt/constraints/inverse_kinematics_constraint.h
- trajopt_ifopt/include/trajopt_ifopt/utils/ifopt_utils.h
- trajopt_ifopt/include/trajopt_ifopt/utils/numeric_differentiation.h
- trajopt_ifopt/include/trajopt_ifopt/variable_sets/joint_position_variable.h
- trajopt_ifopt/src/cartesian_position_constraint.cpp
- trajopt_ifopt/src/collision_constraint.cpp
- trajopt_ifopt/src/inverse_kinematics_constraint.cpp
- trajopt_ifopt/test/cartesian_position_constraint_unit.cpp
- trajopt_ifopt/test/inverse_kinematics_constraint_unit.cpp
- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/qp_problem.h
- trajopt_optimizers/trajopt_sqp/src/qp_problem.cpp
This fix allows const-correctness in downstream projects, for constructions like
```
const Eigen::VectorXd home_position = ...
const auto initial_states = trajopt::interpolate(home_position, ...
```
One potential concern would be non-contiguous memory silently converting to a copy rather than failing to compile. From https://eigen.tuxfamily.org/dox/classEigen_1_1Ref.html: "In the const case, if the input expression does not match the above requirement, then it is evaluated into a temporary before being passed to the function." I didn't see anywhere that would be a concern, and the copy might be faster in some contexts due to improved locality/vectorization, but it's something to be aware of.
> Improve const-correctness of reference passing.

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
- trajopt_ifopt/include/trajopt_ifopt/utils/ifopt_utils.h
- trajopt_ifopt/src/cartesian_position_constraint.cpp
- trajopt_ifopt/src/inverse_kinematics_constraint.cpp
This PR changes the name of the `dofs_fixed` parameter to `fixed_timesteps` to more accurately represent its function. This variable is used [here](https://github.com/ros-industrial-consortium/trajopt_ros/blob/b84e4ae30fa658d2911f3e375bb6009dd8ba7084/trajopt/src/problem_description.cpp#L496-L507) constrain all of the optimization variables in each specified time step to their initial values.
This PR also updates the name of the avoid singularity cost that is printed to the terminal during optimization
> Rename `dofs_fixed` parameter

- trajopt/src/kinematic_terms.cpp
A while back we updated kinematics so that forward and inverse would still calculated the results even if the joint values are outside the joint limits for the purpose of numerically calculated the jacobian. This check is no longer needed.
> Remove checkJoints check no longer needed

- trajopt_ext/osqp_eigen/CMakeLists.txt
- trajopt_ifopt/src/inverse_kinematics_constraint.cpp
- trajopt_ifopt/test/inverse_kinematics_constraint_unit.cpp
The original unit test was setting the seed outside the joint limits.
> Fix trajopt_ifopt inverse kinematics constraint unit test

- trajopt_sco/include/trajopt_sco/optimizers.hpp
- trajopt_sco/src/optimizers.cpp
I'm not sure if this is a good idea or not. I'm testing it out, and it seems promising. However, I'm putting this here so others can test it out.
> Shrink trust region if convex solver fails

- trajopt_sco/src/optimizers.cpp
Currently a timeout is considered a failure, but if constraints are satisfied it should report convergence.
> TrajOpt timeout check constraint convergence and if satisfied report converged

- .github/workflows/windows_noetic_build.yml
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
- trajopt_optimizers/trajopt_sqp/src/osqp_eigen_solver.cpp
- trajopt_optimizers/trajopt_sqp/test/cart_position_optimization_trajopt_sco_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cart_position_optimization_unit.cpp
- trajopt_sco/include/trajopt_sco/modeling.hpp
- trajopt_sco/include/trajopt_sco/osqp_interface.hpp
- trajopt_sco/include/trajopt_sco/solver_interface.hpp
- trajopt_sco/src/modeling.cpp
- trajopt_sco/src/osqp_interface.cpp
- trajopt_sco/src/solver_interface.cpp
The adaptive_rho was change because a unit test was failing [here](https://github.com/tesseract-robotics/trajopt/pull/172) but now passes using the default setting indicating that either there was an issue in OSQP or TrajOpt that has been fixed. Have adaptive_rho enable has a signification impact on planning time so it is reverted to default value now that the setting is exposed.
> Expose convex solver settings and set ospq adaptive_rho to default value

- trajopt_sco/cmake/FindGUROBI.cmake
- trajopt_sco/src/gurobi_interface.cpp
As discussed in Issue https://github.com/tesseract-robotics/trajopt/issues/295, this PR fixes a build issue when compiling the `trajopt_sco` package with gurobi support. Additionally, it updates the cmake routines to account for newer versions of the gurobi solver.
> Build Failure with GUROBI support

- trajopt/src/collision_terms.cpp
- trajopt_ifopt/include/trajopt_ifopt/constraints/collision/collision_types.h
- trajopt_ifopt/src/constraints/collision/collision_types.cpp
- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
- trajopt_ifopt/src/constraints/collision/discrete_collision_evaluators.cpp
- trajopt_sco/src/optimizers.cpp
- trajopt_utils/include/trajopt_utils/utils.hpp
- trajopt_utils/src/utils.cpp
This is an optimization to filter out unused data early to avoid unnecessary calculations when coeff is set to zero for collision pair.
> Filter contact pairs with zero coeffs

- .github/workflows/windows.yml
- trajopt/test/numerical_ik_unit.cpp
- trajopt/test/simple_collision_unit.cpp
- trajopt_ext/qpoases/CMakeLists.txt
- trajopt_ext/qpoases/colcon.pkg
- trajopt_ext/qpoases/package.xml
- trajopt_ext/qpoases/patch_qpoases.cmake
- trajopt_optimizers/trajopt_sqp/test/CMakeLists.txt
- trajopt_sco/include/trajopt_sco/solver_utils.hpp
- trajopt_sco/package.xml
- trajopt_sco/src/qpoases_interface.cpp
- trajopt_sco/src/solver_utils.cpp
- trajopt_sco/test/CMakeLists.txt
This PR adds qpOAESES as an external package on windows. The tests were failing because OSQP is not a great solver for trajopt. The Windows action is updated to use vcpkg master to avoid an error in the most recent release of vcpkg.
> Enable qpOASES on Windows and fix Windows build

- .github/workflows/focal_build.yml
- .github/workflows/unstable_build.yml
- trajopt/test/benchmarks/solve_benchmarks.cpp
- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/numerical_ik_unit.cpp
- trajopt/test/planning_unit.cpp
- trajopt/test/simple_collision_unit.cpp
- trajopt_sco/CMakeLists.txt
- trajopt_sco/cmake/trajopt_sco-config.cmake.in
- trajopt_sco/include/trajopt_sco/bpmpd_interface.hpp
- trajopt_sco/include/trajopt_sco/gurobi_interface.hpp
- trajopt_sco/include/trajopt_sco/optimizers.hpp
- trajopt_sco/include/trajopt_sco/osqp_interface.hpp
- trajopt_sco/include/trajopt_sco/qpoases_interface.hpp
- trajopt_sco/include/trajopt_sco/sco_common.hpp
- trajopt_sco/include/trajopt_sco/solver_interface.hpp
- trajopt_sco/src/bpmpd_interface.cpp
- trajopt_sco/src/gurobi_interface.cpp
- trajopt_sco/src/optimizers.cpp
- trajopt_sco/src/osqp_interface.cpp
- trajopt_sco/src/qpoases_interface.cpp
This replaces #302 and surprised that it was not having issues because the Models themselves needs to be threadsafe. This is why that PR required the omp critical around the addHinge, but does not solve the issue where other constraints are also adding variables and other items to the model which was not threadsafe. 
@marip8 I came up with a way to separate running trajopt with and without multi-threading but not sure if there is a better way.
> Add multi-threaded support to TrajOpt

- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_optimizers/trajopt_sqp/src/trust_region_sqp_solver.cpp
@rjoomen Do you mind reviewing this?
> Fix TrustRegionSQPSolver solve method to correctly set status

- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
- trajopt_ifopt/test/cast_cost_unit.cpp
- trajopt_ifopt/test/continuous_collision_gradient_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/benchmarks/solve_benchmarks.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_attached_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_octomap_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_world_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/planning_unit.cpp
Address this [issue](https://github.com/tesseract-robotics/tesseract_planning/issues/355)
> Fix ifopt continuous collision evaluator to distinguish CONTINUOUS and LVS_CONTINUOUS

- trajopt_optimizers/trajopt_sqp/src/osqp_eigen_solver.cpp
- trajopt_optimizers/trajopt_sqp/test/numerical_ik_unit.cpp
- trajopt_sco/src/osqp_interface.cpp
There were several issues found
1. Not correctly using eigen prune
2. Not using pruned matrix in one case 
3. OSQP Eigen uses a different method for populating the CSC Matrix which has a bug if the input is an empty sparse matrix so a work around was implemented to get around the issue until it is fixed upstream
4. Improve debug output to easily compare between Ifopt and Legacy Version
> Fix osqp_eigen_solver hessian and linear constraint matrix.

- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_optimizers/trajopt_sqp/src/trust_region_sqp_solver.cpp
- Fix termination condition for the trust region loop to match trajopt_sco and the original paper.
- Add initial_merit_error_coeff to match trajopt_sco.
Solves #348
> Fixes to the trust region loop

- .clang-format
- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_sco/include/trajopt_sco/optimizers.hpp
- trajopt_sco/src/optimizers.cpp
- Use member initializers instead of constructor. Allows for showing defaults in doc tooltips or when going to definition. Matches trajopt_sqp.
- Clean up comments
> Use member initializers

- trajopt_common/include/trajopt_common/macros.h
See https://github.com/tesseract-robotics/tesseract/commit/43d08870034e85a3f335d37ded00df282e5ec46e
> Removed gcc-specific option from clang config 

- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/qp_problem.h
- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_optimizers/trajopt_sqp/src/osqp_eigen_solver.cpp
- trajopt_optimizers/trajopt_sqp/src/trust_region_sqp_solver.cpp
- trajopt_sco/src/optimizers.cpp
- trajopt_sco/src/osqp_interface.cpp
- Added max_qp_solver_failures parameter and the logic of TrajOpt to handle solver failures
- Added updateBounds() call after each box size modification
- Moved setVariables() call after a solver failure to solveQPProblem()
- Renamed SQPStatus::TIME_LIMIT to SQPStatus::OPT_TIME_LIMIT because of a name collision with OSQP (in tesseract_planning)
Closes #368
> Handle solver failures like TrajOpt does

- trajopt/include/trajopt/kinematic_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/kinematic_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt/test/kinematic_costs_unit.cpp
- trajopt_sco/include/trajopt_sco/optimizers.hpp
This is to support tolerances on Cartesian waypoints so that you can set constraints that don't have to match perfectly
> Add toleranced Cartesian waypoints to solver

- .github/workflows/windows.yml
Update to v6 of vcpkg-action. v6 optionally uses the new built-in GitHub caching for vcpkg to provide more accurate caching.
> Update to vcpkg-action@v6 and use vcpkg-binarycache

- trajopt/src/kinematic_terms.cpp
Issue causing failed tests in `tesseract_planning`, pointed out in https://github.com/tesseract-robotics/tesseract_planning/pull/389.
> Fixed issue where we were trying to reduce the error in two places

- trajopt_sco/src/osqp_interface.cpp
- trajopt_sco/src/solver_utils.cpp
I noticed significant inefficiencies in creating/updating constraints and costs. With some profiling using perf and hotspot I solved a number of issues leading to a nice speedup for problems with large numbers of variables.
> Trajopt optimizations

- trajopt_sco/include/trajopt_sco/expr_ops.hpp
In expr_ops.hpp reserve() was called at every variable update. This causes the variable and coefficient vectors to be relocated very often, as their size is updated by a minimal amount every time . Removing the reserve() calls allows the vectors to use their normal growing behavior, improving performance.
Before:
After:
> Remove unneeded reserve() calls

- trajopt_ext/osqp/CMakeLists.txt
This updates the downloaded OSQP release to 0.6.3. As can be seen [here](https://github.com/osqp/osqp/releases/tag/v0.6.3), this is just a minor release with hardly any functional changes and none impacting Trajopt. I've been using this for months already, without any problems.
> Update OSQP to 0.6.3

- trajopt/CMakeLists.txt
- trajopt_ifopt/CMakeLists.txt
- trajopt_optimizers/trajopt_sqp/CMakeLists.txt
- trajopt_sco/CMakeLists.txt
Dependencies were still referencing "trajopt-utils" even though that package was replaced with "trajopt-common". Updated to fix cpack building.
> Fix cpack typo to use trajopt_common over trajopt_utils

- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
> Fix incorrect evaluator type check in LVSDiscrete collision evaluator

- trajopt/src/problem_description.cpp
This fixes CollisionEvaluatorType::CONTINUOUS as discussed in #451.
> Fix CollisionEvaluatorType::CONTINUOUS

- trajopt/include/trajopt/collision_terms.hpp
- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt_common/include/trajopt_common/collision_types.h
- trajopt_common/src/collision_types.cpp
This PR removes the weighted sum collision methods from legacy `trajopt`. A number of issues were addressed with these methods during the implementation of `trajopt_ifopt` but they were never backported to legacy `trajopt`. Since the legacy `trajopt` will ultimately be sunset in favor of `trajopt_ifopt`, it doesn't make sense to go through the effort of backporting the fixes. Instead, we will remove them from legacy `trajopt` so users don't run into issues trying to use these methods that are known to have bugs.
> Removed weighted sum methods from legacy Trajopt

- trajopt_common/include/trajopt_common/fwd.h
This struct was removed in a previous commit, but accidentally left in the forward declarations.
> Remove SafetyMarginData from fwd.h

- trajopt_common/CMakeLists.txt
- trajopt_common/include/trajopt_common/collision_types.h
- trajopt_common/include/trajopt_common/yaml_extensions.h
- trajopt_common/src/collision_types.cpp
- trajopt_common/test/CMakeLists.txt
- trajopt_common/test/trajopt_common_yaml_conversions_tests.cpp
For CollisionCoeffData and TrajOptCollisionConfig
> Add yaml conversions and related tests

- .github/workflows/conda.yml
As windows-2019 is unsupported now: https://github.com/actions/runner-images/issues/12045
> Update conda CI to run on windows-2022
