tesseract-robotics/trajopt

- trajopt_sco/src/modeling_utils.cpp
It was previously quadratic for the SQUARED penalty type. This meant that if the coefficient values of one cost were x times larger than another, they were weighted x^2 times as strongly. This is not intuitive for the user, and inconsistent with how other cost functions are set up (such as those is trajectory_costs).
> Changed scaling from coefficients in CostFromErrFunc to be linear for all penalty types.

- trajopt/src/kinematic_terms.cpp
> Jacobian Matrix Dimension Fix

- trajopt/src/trajectory_costs.cpp
> Fixed copy-paste error in JointJerkCost::value

- trajopt/CMakeLists.txt
- trajopt/include/trajopt/file_write_callback.hpp
- trajopt/package.xml
- trajopt/scripts/plot_optimization.py
- trajopt/scripts/traj_compare.py
- trajopt/scripts/traj_graph.py
- trajopt/src/file_write_callback.cpp
- trajopt/src/plot_callback.cpp
- trajopt_examples/launch/glass_up_right_plan.launch
- trajopt_examples/src/glass_up_right_plan.cpp
- trajopt_sco/include/trajopt_sco/modeling.hpp
- trajopt_sco/include/trajopt_sco/optimizers.hpp
- trajopt_sco/src/optimizers.cpp
Adds the file writing callback, two independent python scripts to analyze the files, and a usage example (in glass upright). The most invasive change is the change to the inputs to callback functions. I changed them to accept the entire OptResults object rather than just the x matrix. The plotting callback was updated to match this.
> File writing callback

- trajopt_sco/CMakeLists.txt
- trajopt_sco/cmake/Modules/FindGUROBI.cmake
- trajopt_sco/include/trajopt_sco/gurobi_interface.hpp
- trajopt_sco/src/gurobi_interface.cpp
fixes #34.
What do you think @Levi-Armstrong?
> Updated Gurobi interface

- trajopt_sco/include/trajopt_sco/expr_ops.hpp
- trajopt_sco/src/expr_ops.cpp
- trajopt_sco/test/solver-interface-unit.cpp
I won't pretend that I am an expert, but I think this is what we want. Based on the exprSquare. It does not consider any "shortcuts" if variables are repeated, but a) I am not sure how that would work and b) for our current usecase (multiplying by var=1/t) there would not be a repeated var anyway.
> Add exprMult(AffExpr, AffExpr)

- trajopt/include/trajopt/problem_description.hpp
- trajopt/include/trajopt/trajectory_costs.hpp
- trajopt/src/problem_description.cpp
- trajopt/src/trajectory_costs.cpp
- trajopt_examples/launch/glass_up_right_plan.launch
- trajopt_examples/src/basic_cartesian_plan.cpp
- trajopt_examples/src/car_seat_demo.cpp
- trajopt_examples/src/glass_up_right_plan.cpp
- trajopt_examples/src/puzzle_piece_auxillary_axes_plan.cpp
- trajopt_examples/src/puzzle_piece_plan.cpp
Fixes #55 and a few other things that I have found along the way.
> Bug fixes for examples

- trajopt_examples/launch/pick_and_place_plan.launch
- trajopt_examples/src/pick_and_place_plan.cpp
Fixes the indexing on the place move. Also allows steps_per_phase to be set in the launch file and adds 4 more place locations.
> pick_and_place example Improvements

- trajopt_sco/include/trajopt_sco/num_diff.hpp
changed to take by reference in std::function
> ScalarOfVector, VectorOfVector, MatrixOfVector function signature

- trajopt/src/problem_description.cpp
@mpowelson I am disabling the jacobian calculator for cart pose and dynamic cart pose. It appears to be intermittently providing incorrect results.
> Disable jacobian calculator for cart pose and dynamic cart pose

- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
This adds a user defined term info to allow constraints or cost from error function to directly be added to the problem.
> Add user defined term info

- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/planning_unit.cpp
This should be merged after the current tesseract [PR](https://github.com/ros-industrial-consortium/tesseract/pull/192) gets merged.
> Update test due to changes in tesseract checkTrajectory

- trajopt/include/trajopt/kinematic_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/include/trajopt/utils.hpp
- trajopt/src/kinematic_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt/src/utils.cpp
This PR adds a cost function and gradient for avoiding kinematic singularities by maximizing the smallest singular value of the robot Jacobian at a given pose.
> Avoid singularity cost

- trajopt/include/trajopt/typedefs.hpp
- trajopt_sco/include/trajopt_sco/modeling_utils.hpp
- trajopt_sco/src/modeling_utils.cpp
Eigen documentation state that Eigen types should always be passed by reference. This PR fixes locations where Eigen types are passed by value.
> Change Eigen arguments that are passed by value to reference

- .travis.yml
- dependencies.rosinstall
This is a new dependency of opw_kinematics
> Add cmake_common_scripts to rosinstall

- trajopt/include/trajopt/problem_description.hpp
- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/joint_costs_unit.cpp
- trajopt/test/kinematic_costs_unit.cpp
- trajopt_ext/vhacd/src/VHACD.cpp
- trajopt_ifopt/test/cartesian_position_constraint_unit.cpp
- trajopt_ifopt/test/cast_cost_unit.cpp
- trajopt_ifopt/test/collision_unit.cpp
- trajopt_ifopt/test/inverse_kinematics_constraint_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cart_position_optimization_trajopt_sco_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cart_position_optimization_unit.cpp
- trajopt_sco/CMakeLists.txt
This depends on Tesseract [PR](https://github.com/ros-industrial-consortium/tesseract/pull/383)
> Fix warnings and update to use tesseract Manipulator Manager

- trajopt_ifopt/include/trajopt_ifopt/constraints/collision_evaluators.h
- trajopt_ifopt/src/collision_constraint.cpp
- trajopt_ifopt/src/collision_evaluators.cpp
> Add additional collision evaluators

- trajopt/include/trajopt/problem_description.hpp
- trajopt/src/problem_description.cpp
Port #226 changes to feature/CommandLanguage branch
> Rename dofs_fixed parameter

- trajopt_sco/src/osqp_interface.cpp
> Fix memory leak in osqp_interface

- trajopt/src/problem_description.cpp
> Fix misnaming of constraints

- trajopt/src/problem_description.cpp
- trajopt/src/trajectory_costs.cpp
> Correctly use lower_tol in JointPosIneqCost AffExpr 

- .github/workflows/windows_noetic_build.yml
- trajopt/src/trajectory_costs.cpp
- trajopt/test/joint_costs_unit.cpp
Closes #251. I'm pretty sure this fixes it. However OSQP was still having a hard time solving QPs with this in it. I decided to not worry about it since I hope to upgrade to trajopt_ifopt before too long anyway.
> Fix JointPosIneqConstraint

- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/interface_unit.cpp
- trajopt/test/joint_costs_unit.cpp
- trajopt/test/kinematic_costs_unit.cpp
- trajopt/test/numerical_ik_unit.cpp
- trajopt/test/planning_unit.cpp
- trajopt/test/simple_collision_unit.cpp
- trajopt_ifopt/test/cast_cost_unit.cpp
- trajopt_ifopt/test/collision_unit.cpp
- trajopt_ifopt/test/continuous_collision_gradient_unit.cpp
- trajopt_ifopt/test/discrete_collision_gradient_unit.cpp
- trajopt_ifopt/test/simple_collision_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_attached_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_octomap_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/cast_cost_world_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/numerical_ik_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/planning_unit.cpp
- trajopt_optimizers/trajopt_sqp/test/simple_collision_unit.cpp
Supports [Tesseract 672](https://github.com/tesseract-robotics/tesseract/pull/672)
> Remove unused header

- .clang-tidy
- .github/workflows/focal_build.yml
- trajopt/include/trajopt/collision_terms.hpp
- trajopt/include/trajopt/problem_description.hpp
- trajopt/test/cast_cost_attached_unit.cpp
- trajopt/test/cast_cost_octomap_unit.cpp
- trajopt/test/cast_cost_unit.cpp
- trajopt/test/cast_cost_world_unit.cpp
- trajopt/test/joint_costs_unit.cpp
- trajopt/test/planning_unit.cpp
- trajopt/test/simple_collision_unit.cpp
- trajopt_ifopt/src/constraints/collision/collision_utils.cpp
- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
- trajopt_ifopt/src/constraints/collision/discrete_collision_evaluators.cpp
- trajopt_ifopt/src/constraints/joint_acceleration_constraint.cpp
- trajopt_ifopt/src/constraints/joint_jerk_constraint.cpp
- trajopt_ifopt/src/constraints/joint_velocity_constraint.cpp
- trajopt_optimizers/trajopt_sqp/test/simple_collision_unit.cpp
- trajopt_utils/include/trajopt_utils/logging.hpp
- trajopt_utils/src/clock.cpp
- trajopt_utils/src/logging.cpp
Supports [Tesseract 672](https://github.com/tesseract-robotics/tesseract/pull/672)
> Add ContactManagerConfig inside CollisionCheckConfig

- trajopt_ifopt/src/costs/absolute_cost.cpp
Fixes #289. @johnwason's fix unfortunately did not work, as with OpenMP SparseView() still failed.
> Fixes SparseView issue

- trajopt_ifopt/package.xml
- trajopt_optimizers/trajopt_sqp/package.xml
- trajopt_sco/package.xml
- trajopt_utils/package.xml
> catkin dependency for ROS1 only

- trajopt/src/collision_terms.cpp
- trajopt/src/problem_description.cpp
- trajopt_ifopt/src/constraints/collision/collision_utils.cpp
This is a major bug causing undefined behavior which has been in TrajOpt for sometime.
> Fix undefined behavior bug in processInterpolatedCollisionResults

- trajopt_sco/src/optimizers.cpp
Modified two LOG_ERROR calls to be LOG_WARN, as they are not true ERRORs and clutter the screen logs.
> Updated optimizer error reporting. Downgraded two ERRORs to WARNs

- trajopt_ifopt/include/trajopt_ifopt/constraints/collision/collision_types.h
- trajopt_ifopt/include/trajopt_ifopt/constraints/collision/continuous_collision_evaluators.h
- trajopt_ifopt/include/trajopt_ifopt/constraints/collision/discrete_collision_evaluators.h
- trajopt_ifopt/src/constraints/collision/collision_types.cpp
- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
- trajopt_ifopt/src/constraints/collision/discrete_collision_evaluators.cpp
> Rename setPairCollisionMarginData to setPairCollisionCoeff

- trajopt_common/include/trajopt_common/collision_utils.h
- trajopt_common/src/collision_utils.cpp
- trajopt_ifopt/include/trajopt_ifopt/constraints/collision/continuous_collision_evaluators.h
- trajopt_ifopt/src/constraints/collision/continuous_collision_evaluators.cpp
- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_optimizers/trajopt_sqp/src/trust_region_sqp_solver.cpp
> Fix trajopt ifopt collision with fixed states

- trajopt_sco/src/osqp_interface.cpp
See https://github.com/tesseract-robotics/trajopt/issues/373
> Use OSQP_INFTY instead of numeric_limits infinity

- trajopt_optimizers/trajopt_sqp/include/trajopt_sqp/types.h
- trajopt_sco/include/trajopt_sco/optimizers.hpp
> Fix trust region params boost serialization

- trajopt/src/collision_terms.cpp
- trajopt_common/src/collision_utils.cpp
- trajopt_ifopt/src/constraints/collision/discrete_collision_evaluators.cpp
Minor updates per commit messages and post-merge review from #455
> Minor updates
